routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::namespace('Admin')->group(function () {
    Route::namespace('User')->group(function () {
        Route::get('buymin/login', 'LoginController@showLoginForm')->name('admin.login');
        Route::post('buymin/login', 'LoginController@login')->name('admin.login');
        Route::get('buymin/logout', 'LoginController@logout')->name('admin.logout');
    });
});

Route::group([
    'prefix' => 'buymin',
    'middleware' => ['admin'],
    'as' => 'admin.'
], function () {
    Route::namespace('Admin')->group(function () {
        Route::namespace('Brand')->group(function () {
            Route::resource('brand', 'BrandController');
            Route::get('remove-image-brand', 'BrandController@removeImage')->name('brand.remove.image');
        });
        Route::namespace('Category')->group(function () {
            Route::resource('category', 'CategoryController');
            Route::get('remove-image-category', 'CategoryController@removeImage')->name('category.remove.image');
            Route::get('categories-tree', ['uses' => 'CategoryController@getTree', 'as' => 'category.getTree']);
        });
        Route::namespace('Dashboard')->group(function () {
            Route::get('/', 'DashboardController@index')->name('dashboard');
        });
        Route::namespace('Product')->group(function () {
            Route::resource('product', 'ProductController');
            Route::get('remove-image-product', 'ProductController@removeImage')->name('product.remove.image');
            Route::get('remove-image-thumb', 'ProductController@removeThumbnail')->name('product.remove.thumb');
        });
        Route::namespace('Scraper')->group(function () {
            Route::resource('scrapercollection', 'ScraperCollectionController');
        });
        Route::namespace('Shop')->group(function () {
            Route::resource('shop', 'ShopController');
            Route::get('remove-image-logo', 'ShopController@removeImage')->name('shop.remove.logo');
        });
        Route::namespace('Slider')->group(function () {
            Route::resource('slider', 'SliderController');
            Route::get('remove-image-image_desktop', 'SliderController@removeImageDesktop')->name('slider.remove.image_desktop');
            Route::get('remove-image-image_mobile', 'SliderController@removeImageMobile')->name('slider.remove.image_mobile');
        });
        Route::namespace('User')->group(function () {
            Route::resource('user', 'UserController');
        });
    });
});

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Sitemaps
Route::namespace('Front')->group(function () {
    Route::namespace('Sitemap')->group(function () {
        Route::get('/sitemap/brands.xml', 'SitemapController@brands');
        Route::get('/sitemap/categories.xml', 'SitemapController@categories');
        Route::get('/sitemap/shops.xml', 'SitemapController@shops');
        Route::get('/sitemap/products.xml', 'SitemapController@productindex');
        Route::get('/sitemap/products-{slug}.xml', 'SitemapController@products');
    });
});

Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => [ 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]
    ], function() {

        // Homepage & Product Routes
        Route::namespace('Front')->group(function () {
            Route::namespace('Homepage')->group(function () {
                Route::get('/', 'HomepageController@index')->name('front.home.index');
            });
            Route::namespace('Product')->group(function () {
                Route::get('compare-prices/{slug}.html', 'ProductController@getProduct')->name('front.product.slug');
                Route::get("search", 'ProductController@search')->name('search.product');
            });
        });

        // Brand Routes
        Route::group([
            'prefix' => 'compare-brands',
            'as' => 'front.'
        ], function () {
            Route::namespace('Front')->group(function () {
                Route::namespace('Brand')->group(function () {
                    Route::get('/', 'BrandController@index')->name('brand.index');
                    Route::get('{brand}.html', 'BrandController@show')->name('get.brand');
                });
            });
        });

        // Category Routes
        Route::group([
            'prefix' => 'all-categories',
            'as' => 'front.'
        ], function () {
            Route::namespace('Front')->group(function () {
                Route::namespace('Category')->group(function () {
                    Route::get('/', 'CategoryController@index')->name('category.index');
                });
            });
        });

        Route::group([
            'as' => 'front.'
        ], function () {
            Route::namespace('Front')->group(function () {
                Route::namespace('Category')->group(function () {
                    Route::get('{slug}.html', 'CategoryController@getCategory')->name('category.view');
                });
            });
        });


        // Shop Routes
        Route::group([
            'prefix' => 'online-shopping-uae',
            'as' => 'front.'
        ], function () {
            Route::namespace('Front')->group(function () {
                Route::namespace('Shop')->group(function () {
                    Route::get('/', 'ShopController@index')->name('shop.index');;
                    Route::get('{slug}.html', 'ShopController@show')->name('shop.show');
                });
            });
        });
    });

app/Http/Controllers/Admin/Scraper/ScraperCollectionController.php
<?php
/**
 * Created by PhpStorm.
 * User: ruudvanengelenhoven
 * Date: 07/06/2018
 * Time: 10:14
 */

namespace App\Http\Controllers\Admin\Scraper;

use App\Cms\Categories\Models\Category;
use App\Cms\Scrapers\Interfaces\ScraperCollectionRepositoryInterface;
use App\Cms\Scrapers\Requests\CreateScraperCollectionRequest;
use App\Cms\Shops\Models\Shop;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Http\UploadedFile;

class ScraperCollectionController extends Controller
{
    /**
     * @var ScraperCollectionRepositoryInterface
     */
    private $scraperCollectionRepo;

    /**
     * ShopController constructor.
     * @param ScraperCollectionRepositoryInterface $scraperCollectionRepo
     */
    public function __construct(ScraperCollectionRepositoryInterface $scraperCollectionRepo)
    {
        $this->scraperCollectionRepo = $scraperCollectionRepo;
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        return view('admin.scraper.collection.index',
            ['collections' => $this->scraperCollectionRepo->listScraperCollections('id', 'asc')]
        );
    }

    /**
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function create()
    {
        $shops = Shop::get()->sortBy('name');
        $categories = Category::where('parent_id', NULL)->with('kids')->get()->sortBy('sort_order');

        return view('admin.scraper.collection.create', [
            'categories' => $categories,
            'shops' => $shops,
        ]);
    }

    public function store(CreateScraperCollectionRequest $request)
    {
        $request['categories'] = collect($request['categories'])->implode(',');
        $data = $request->except('_token', '_method');

        $this->scraperCollectionRepo->createScraperCollection($data);

        $request->session()->flash('message', 'Scraper Collection is successfully created');
        return redirect()->route('admin.scrapercollection.index');
    }

    public function destroy(int $id)
    {
        $scraper = $this->scraperCollectionRepo->findScraperCollectionById($id);
        $scraper->delete();

        request()->session()->flash('message', 'Delete successful');
        return redirect()->route('admin.scrapercollection.index');
    }
}

resources/views/admin/scraper/collection/create.blade.php
@extends('layouts.admin.app')

@section('content')

    @include('layouts.errors-and-messages')

    <form action="{{ route('admin.scrapercollection.store') }}" method="post" enctype="multipart/form-data">
        {{ csrf_field() }}

        <div class="card">
            <div class="card-body">
                <h3 class="card-title">Add new Collection</h3>
                @include('layouts.shared.fields.input', [
                    'title' => 'Name',
                    'name' => 'name',
                    'type' => 'text',
                    'required' => 'true'
                    ])
                @include('layouts.shared.fields.input', [
                    'title' => 'URL',
                    'name' => 'collection',
                    'type' => 'text',
                    'required' => 'true'
                    ])

                <div class="form-group">
                    <label for="shop_id" class="form-label">Shop</label>
                    <select id="shop_id" name="shop_id" class="form-control custom-select">
                        @foreach($shops as $shop)
                            <option value="{{ $shop->id }}">{{ $shop->name }}</option>
                        @endforeach
                    </select>
                </div>
            </div>
        </div>

        <div class="card">
            <div class="card-header">
                <h5 class="mb-0">Categories</h5>
            </div>
            <div class="card-body">
                <div id="tree">
                    @include('admin.scraper.collection.includes.categories', ['categories' => $categories])
                </div>
            </div>
        </div>
        <div class="card-footer text-right">
            <div class="d-flex">
                <a href="{{ route('admin.scrapercollection.index') }}" class="btn btn-link">Cancel</a>
                <button type="submit" class="btn btn-primary ml-auto">Add ScraperCollection</button>
            </div>
        </div>
    </form>

@endsection

@section('footerjs')
    <script src="{{ asset('//cdn.ckeditor.com/4.8.0/standard/ckeditor.js') }}"></script>
@endsection

resources/views/admin/scraper/collection/index.blade.php
@extends('layouts.admin.app')

@section('content')

    @include('layouts.errors-and-messages')
    <div class="card">
        <div class="card-header">
            <h3 class="card-title">Manage Scraper Collections</h3>
            <div class="card-options">
                <a href="{{ route('admin.scrapercollection.create') }}" class="btn btn-outline-primary btn-sm float-right"><i class="fe fe-plus mr-2"></i>Add Scraper Collection</a>
            </div>
        </div>
        <div class="card-body table-responsive">
            <table class="table card-table table-vcenter">
                <thead>
                <tr>
                    <th>id</th>
                    <th>Name</th>
                    <th>Shop</th>
                    <th></th>
                    <th></th>
                </tr>
                </thead>
                <tbody>
                    @foreach($collections as $collection)
                        <tr>
                            <td>{{ $collection->id }}</td>
                            <td>{{ $collection->name }}</td>
                            <td>{{ $collection->shop->name }}</td>
                            <td class="w-1">
                                <form action="{{ route('admin.scrapercollection.destroy', $collection->id) }}" method="post">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="delete">
                                    <div class="btn-group">
                                        <button onclick="return confirm('Are you sure?')" type="submit" class="btn icon" style="padding:0; background:transparent">
                                            <i class="fe fe-trash"></i>
                                        </button>
                                    </div>
                                </form>
                            </td>
                            <td class="w-1">
                                <a class="icon" href="{{ route('admin.scrapercollection.edit', $collection->id) }}">
                                    <i class="fe fe-edit"></i>
                                </a>
                            </td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        </div>
    </div>

@endsection